### ISSUE TITLE
can we have highlight on "#define" and "using vec = vector<int>" that self define type

### ISSUE THREAD

**Issue by nameless-user12138** [bfrg/vim-cpp-modern#11]
![image](https://user-images.githubusercontent.com/54355449/98082537-de26dc00-1eb3-11eb-9061-05d0665e7a28.png)

**Comment by bfrg** [comment]
Do you want the second `ll` to be highlighted because it's defined above using `#define`? I don't quite understand what you want.

**Comment by nameless-user12138** [comment]
Yes, oh my poor English

**Comment by bfrg** [comment]
This is not possible. And I don't have intentions to add this feature since it's too complicated to do with pure `vimscript`. There are other plugins that highlight keywords using the tags found in the current file/project with `ctags`.
See for example:
- https://github.com/abudden/taghighlight-automirror
- https://vim8.org/scripts/script.php?script_id=1232
