### ISSUE TITLE
std::ref and std::cref

### ISSUE THREAD

**Issue by Bbllaaddee** [bfrg/vim-cpp-modern#18]
Hey there!

I noticed that standard library function templates `std::ref` and `std::cref` are not highlighted.

Introduced in c++11 as helper functions for std::reference_wrapper (which is highlighted): https://en.cppreference.com/w/cpp/utility/functional/ref

**Comment by Bbllaaddee** [comment]
Experimented a bit, it seems that only types are highlighted...

**Comment by bfrg** [comment]
Can you show example code? 

Functions are highlighted with `let g:cpp_no_function_highlight = 0`. Let me change the variable to `g:cpp_function_highlight`. The negation is confusing.

**Comment by bfrg** [comment]
If you have code like `std::ref(foo)`, `ref` will be highlighted as `Function` by default.

**Comment by Bbllaaddee** [comment]
Hey there!

What I meant was it is not highlighted when used without parentheses, for example, if you pass a function to an algorithm.

Like
```c++
std::transform(vec.begin(), vec.end(), vec.begin(), sqrt);
``` 

The `sqrt`, which is a member of the std is not highlighted (just an example).
Although, I'm not sure, if that's a good idea)

**Comment by bfrg** [comment]
Any word that appears before an opening parenthesis is highlighted as a function. The highlighting of functions is purely regex-based. I deliberately didn't add the function names from the standard library because there are just too many and often the names collide with some types or user-defined variables (I noticed this in the past with `vim-cpp-enhanced-highlight` - one of the reason I started this repo). In most cases the current approach works fine, your example above is one of the exceptions. If you need more accurate highlighting, you need to look for a LSP plugin that supports semantic highlighting.
