### ISSUE TITLE
no highlight for from_chars

### ISSUE THREAD

**Issue by laoshaw** [bfrg/vim-cpp-modern#29]
is keyword highlight complete for c++17, could not find from_chars at least

**Comment by bfrg** [comment]
`std::from_chars()` is a function, see [cppreference](https://en.cppreference.com/w/cpp/utility/from_chars). It should be highlighted as a function, unless you have `let g:cpp_function_highlight = 0`.

Function highlighting is not keyword based because there would be too many keywords we would have to keep track of. Instead, for functions we use a regex-based approach. Every word that is followed by an opening parenthesis is highlighted as a function.

Keyword highlighting should be complete for C++17. If you find something else missing, feel free to open a new issue.

**Comment by bfrg** [comment]
Just noticed that some types are missing: `std::from_chars_result`, `std::to_chars_result` and `std::chars_format`.
